{% set name = "ml_dtypes" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ml_dtypes-{{ version }}.tar.gz
  sha256: 6488eb642acaaf08d8020f6de0a38acee7ac324c1e6e92ee0c0fea42422cb797

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - numpy >=1.21.2  # [py<311]
    - numpy >=1.23.3  # [py>=311]
    - pybind11 2.10
    - setuptools >=67.6.0,<68
    - pip
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ml_dtypes
  commands:
    - pip check
    - pytest -n auto
  source_files:
    - ml_dtypes/tests
  requires:
    - pip
    - pytest
    - pytest-xdist
    - absl-py

about:
  home: https://pypi.org/project/ml-dtypes/
  summary: A stand-alone implementation of several NumPy dtype extensions used in machine learning libraries
  description: |
    ml_dtypes is a stand-alone implementation of several NumPy dtype extensions used in machine learning libraries, including:
    bfloat16: an alternative to the standard float16 format
    float8_*: several experimental 8-bit floating point representations including:
      float8_e4m3b11fnuz, float8_e4m3fn, float8_e4m3fnuz, float8_e5m2, float8_e5m2fnuz
    int4 and uint4: low precision integer types.
  dev_url: https://github.com/jax-ml/ml_dtypes
  doc_url: https://github.com/jax-ml/ml_dtypes
  # Mozilla license is also present, but only applies to pre-compiled wheels.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
