{% set name = "ml_dtypes" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ml_dtypes-{{ version }}.tar.gz
  sha256: 95ce33057ba4d05df50b1f3cfefab22e351868a843b3b15a46c65836283670c9

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - numpy {{ numpy }}
    - setuptools >=80.8.0,<80.9.dev0
    - pip
    - numpy >=2.0,<3.dev0
  run:
    - python
    - numpy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ml_dtypes
  requires:
    - pip
  commands:
    - pip check
    # Maintainers dropped tests from source builds, we may want to build from source if problems are found.

about:
  home: https://pypi.org/project/ml-dtypes/
  summary: A stand-alone implementation of several NumPy dtype extensions used in machine learning libraries
  description: |
    ml_dtypes is a stand-alone implementation of several NumPy dtype extensions used in machine learning libraries, including:
    bfloat16: an alternative to the standard float16 format
    float8_*: several experimental 8-bit floating point representations including:
    float8_e4m3b11fnuz, float8_e4m3fn, float8_e4m3fnuz, float8_e5m2, float8_e5m2fnuz
    int4 and uint4: low precision integer types.
  dev_url: https://github.com/jax-ml/ml_dtypes
  doc_url: https://github.com/jax-ml/ml_dtypes
  # Mozilla license is also present, but only applies to pre-compiled wheels.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
